// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Entidades.SqlServer.Documentos_Guarco", b =>
                {
                    b.Property<int>("id_documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fecha_aprobacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_finalizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_revision_finalizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_revision_inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre_area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_documento");

                    b.ToTable("Documentos_Guarco");
                });
#pragma warning restore 612, 618
        }
    }
}
